version: "3.8"
services: 
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=rustyhermansensoftwareengineer.link
      - SUBDOMAINS=www,
      - VALIDATION=http
    volumes:
      - ./nginx/default:/config/default
      # - ./nginx/default.conf:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  react-app:
    container_name: portfolio_frontend
    build: ./React
    # image: rusty23/portfolio
    stdin_open: true
    volumes:
      - ./React/default.conf:/etc/nginx/conf.d/default.conf 
  api-server:                           #node api
    container_name: portfolio_backend
    build: ./backend
    # image: rusty23/portfolio-api
    environment: 
      DB_HOST: db
      DB_PORT: 5432
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on: 
      - db

  db:
    container_name: portfolio_database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rusty
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql


 
