name: "db_backup"

on:
  schedule:
    - cron: "*/1 * * * *" 

jobs:
  build: 
    name: db_backup
    runs-on: self-hosted
    steps: 
      - name: backup_database
        run: 
          docker exec -t portfolio_database pg_dumpall -c -U postgres  dump_`date +`%m-%d-%Y"_"%H_%M_%S`.sql
