name: "db_make_backup"

on:
  schedule:
    - cron: "*/1 * * * *" 

jobs:
  db_backup: 
    name: db_backup
    runs-on: [self-hosted, db_make_backup]
    steps: 
      - name: backup_database
        run: |
          cd /home/rusty/backups
          docker exec portfolio_database pg_dump -U rusty -F t postgres> dump_`date +%d-%m-%Y`.sql
  pull_backup:
    runs-on: [self-hosted, pull_backup]
    needs: [db_backup]
    steps: 
      - name: pull backup
        run: |
          find /home/rusty/backups/ -mtime +30 -name '*.sql' -exec rm -rf {} \;
          sudo wg-quick up rustyvpn
          scp root@10.200.30.1:/home/rusty/backups/* /home/rusty/backups
          sudo wg-quick down rustyvpn
  cleanse:
    name: cleanse
    runs-on: [self-hosted, db_make_backup]
    needs: [pull_backup]
    steps: 
      - name: cleanse
        run: |
          rm /home/rusty/backups/*
  
