name: "db_make_backup"

# on:
#   schedule:
#     - cron: "*/1 * * * *" 

on: 
  push:
    branches: [main]

jobs:
  db_backup: 
    name: db_backup
    runs-on: [self-hosted, db_make_backup]
    steps: 
      - name: backup_database
        run: |
          cd /home/rusty/backups
          docker exec -t portfolio_database pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
  pull_backup:
    runs-on: [self-hosted, pull_backup]
    steps: 
      - name: pull backup
        run: |
          sudo wg-quick up rustyvpn
          sudo scp root@10.200.30.1:/home/rusty/backups/* /home/rusty/backups
          sudo wg-quick down rustyvpn
  cleanse:
    name: cleanse
    runs-on: [self-hosted, db_make_backup]
    steps: 
      - name: cleanse
        run: |
          rm /home/rusty/backups/*
  
