name: "db_make_backup"

# on:
#   schedule:
#     - cron: "*/1 * * * *" 

on: 
  push:
    branches: [main]

jobs:
  db_make_backup: 
    name: db_make_backup
    runs-on: [self-hosted, db_make_backup]
    steps: 
      - name: backup_database
        run: |
          rm /home/rusty/backups/*
          cd /home/rusty/backups
          docker exec -t portfolio_database pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
