name: "restore_db"

on: 
  workflow_dispatch:
    inputs:
      date:
        description: "Enter date of backup to restore"
        required: true

jobs: 
  get_restore_file: 
    name: get_backup_file
    runs-on: [self-hosted, pull_backup]
    steps:
      - name: get_file
        run: |
          sudo wg-quick up rustyvpn
          scp /home/rusty/backups/dump_${{github.event.inputs.date}}.sql root@10.200.30.1:/home/rusty/restore/restore.sql
          sudo wg-quick down rustyvpn
  db_restore:
    name: restore
    runs-on: [self-hosted, backup]
    needs: [get_restore_file]
    steps:
      - name: restore
        run: |
          docker exec -i portfolio_database pg_restore -U rusty -c -v -d postgres < /home/rusty/restore/restore.sql

