name: "deploy"

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.4.0
        with: 
          fetch-depth: 100

      - name: build and test
        run: |
          git secret reveal
          docker-compose up --build -d
          cd adminBackend
          npm install
          pm2 start process.yml