name: "pull_backup"

# on:
#   schedule: 
#     - cron: "*/1 * * * *"

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build:
    runs-on: [self-hosted, pull_backup]
    steps: 
      - name: pull backup
        run: |
          sudo wg-quick up rustyvpn
          sudo scp root@10.200.30.1:/home/rusty/backups/* /home/rusty/backups
          rm /home/rusty/backups/*
          cd /home/rusty 
          sudo wg-quick down rustyvpn