name: "pull_backup"

on:
  schedule: 
    - cron: "0 11 * * 1"

jobs: 
  build:
    runs-on: self-hosted
    steps: 
      - name: pull backup
        run: 
          sudo wg-quick up rustyvpn
          file_to_copy =`ssh`
          sudo scp root@10.200.30.1:/home/rusty/'ls -t /home/rusty/ | head -l' /home/rusty
          sudo wg-quick down rustyvpn